apiVersion: apps/v1
kind: Deployment
metadata:
  name: adif-parser-service
  namespace: adif-parser-service
spec:
  selector:
    matchLabels:
      app: adif-parser-service
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: adif-parser-service
    spec:
      containers:
        - name: adif-parser-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: http
          resources: {{ toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
